### ISSUE TITLE
Nested query params handled via qs library don't trigger request when changed

### ISSUE THREAD

**Issue by uxxman** [reactive/data-client#3280]
**React version**: 18.3.1

**TypeScript version**: 5.6.3

**Reactive Data Client version**: 0.14.16

**Package manager version**: npm 10

**Environment version**: all via Expo

**Describe the bug**
We have had discussions in the past regarding query string params being objects (https://github.com/reactive/data-client/issues/348) and it was nice that you allowed customisation via qs package to be used to handle them (https://dataclient.io/rest/api/RestEndpoint#using-qs-library). This works and the request is sent correctly but the issue now is even when a new request is sent with some params changed, the new request is not fired cause I thing the entity meta still considers it the same request as before. Looking at the debugger it looks like the meta still stores the nested object as [object object] and not how qs stringify it.
  
<img width="929" alt="Screenshot 2024-11-24 at 00 20 39" src="https://github.com/user-attachments/assets/ddc22af7-b325-4687-8e9b-0f38ea261787">

**To Reproduce**
The issue can be produced by having 2 screens
* one showing all post with query string  **search[published]=true**
* other showing my favourite posts with query string  **search[favourite]=true**

The request is only sent for which ever screen loads first, navigating to the other screen does not fire any new request and just show posts loaded by the previous screen request.

**Comment by ntucker** [comment]
Thanks for the report! Can you provide the entity's pk() definition? This is used to produce the object key you mentioned.

**Comment by ntucker** [comment]
Quick answer is that https://dataclient.io/rest/api/Collection#argsKey must also be set.  I'll update the docs today

**Comment by ntucker** [comment]
Can you provide the args you used for my test case?

**Comment by uxxman** [comment]
You mean which args fail for me?

Screen One with =>   search[type]=coupon
Screen Two with =>   search[type]=cashback

Point to note, if I remain on screen One and use a button and useState to change type to cashback, a request is fired. So, same instance of useSuspense handles the param change. Only the new useSuspense on a different screen fails to detect a new request with params changed

**Comment by uxxman** [comment]
Also, providing asgsKey doesn't change the outcome

**Comment by uxxman** [comment]
if I force add a non-object param to the query string, things start to work as expected. i.e

Screen One with => a=1&search[type]=coupon
Screen Two with => a=2&search[type]=cashback

**Comment by ntucker** [comment]
> You mean which args fail for me?
> 
> Screen One with => search[type]=coupon Screen Two with => search[type]=cashback
> 
> Point to note, if I remain on screen One and use a button and useState to change type to cashback, a request is fired. So, same instance of useSuspense handles the param change. Only the new useSuspense on a different screen fails to detect a new request with params changed

Can you provide the usage in [useSuspense()](https://dataclient.io/docs/api/useSuspense), rather than the serialized form?

**Comment by uxxman** [comment]
```js
// Screen One

const defaultFilters = {
  search: {
    type: 'Coupon'
  }
};

function ScreenOne() {
  const [filters, setFilters] = useState(defaultFilters);
  const { items: offers, meta } = useSuspense(OfferResource.getList, filters);
  
  // display logic
}
```

```js
// Screen Two

const defaultFilters = {
  search: {
    type: 'Cashback'
  }
};

function ScreenTwo() {
  const [filters, setFilters] = useState(defaultFilters);
  const { items: offers, meta } = useSuspense(OfferResource.getList, filters);
  
  // display logic
}
```

**Comment by uxxman** [comment]
So the issue seems to be that the store meta is not using the string value given by QS package but again somewhere using normal url stringify so it ends up with "search":"[object Object]" and thus treat all requests as same request no matter what we set in search object.

**Comment by ntucker** [comment]
The problem is in the Collection pk definition. I already have a fix, I'm just working on the tests.

**Comment by uxxman** [comment]
any plan for a release soon? i see you also upgraded react-navigation to support v7.

**Comment by ntucker** [comment]
yeah, just working on react-19-rc.1 upgrade now
